import React from "react";
import Link from "next/link";
import Image from "next/image";

export const metadata = {
  title: "Food Poison Detection Kit (STPD-06) | Marshal Marketing & Management",
  description: "Official specifications for the STPD-06 Short Term Poison Detection Kit used by US DOD and international defense entities.",
};

const features = [
  <><strong>Highly Portable:</strong> The STPD series kits are very small and light weight. They can therefore be easily stored or transported by land or air with the VIP or person to be protected.</>,
  <><strong>Autonomous Operation:</strong> Designed to be totally autonomous kits that <strong>REQUIRE NO ADDITIONAL MATERIAL</strong> that is not in the Kit itself, except for clean water.</>,
  <><strong>Zero Technical Barriers:</strong> They require <strong>NO Electricity</strong>, <strong>NO Batteries</strong> and <strong>NO knowledge of chemistry</strong> from the users.</>,
  <><strong>Immediate Intuitive Reading:</strong> By design, a <strong>POSITIVE color change</strong> will be the indicator of the presence of poison, so that it will be recognizable by any person IMMEDIATELY.</>,
];

function CheckIcon() { return <svg viewBox="0 0 24 24" fill="none" className="h-3.5 w-3.5" stroke="currentColor" strokeWidth="3"><path d="m5 12 4.5 4.5L19 7" /></svg>; }

function AiOrbitalVisual() {
  return <div aria-hidden="true" className="absolute inset-0 overflow-hidden pointer-events-none">
    <div className="field-grid absolute inset-0 opacity-30" />
    <div className="absolute right-[12%] top-1/2 h-48 w-48 -translate-y-1/2 rounded-full border border-cyan-200/20 md:h-72 md:w-72" />
    <div className="orbit-one absolute right-[12%] top-1/2 h-48 w-48 -translate-y-1/2 rounded-full border border-cyan-200/30 md:h-72 md:w-72"><span className="absolute -top-1 left-1/2 h-2.5 w-2.5 rounded-full bg-cyan-200 shadow-[0_0_18px_7px_rgba(103,232,249,.55)]" /></div>
    <div className="orbit-two absolute right-[16%] top-1/2 h-36 w-36 -translate-y-1/2 rounded-full border border-blue-300/20 md:h-52 md:w-52"><span className="absolute -bottom-1 left-1/2 h-2 w-2 rounded-full bg-blue-300" /></div>
    <div className="ai-cube absolute right-[21%] top-1/2 h-20 w-20 -translate-y-1/2 rotate-45 border border-cyan-200/35 bg-cyan-300/10 shadow-[0_0_55px_rgba(34,211,238,.2)] md:h-28 md:w-28" />
  </div>;
}

export default function FoodPoisonDetectionKit() {
  return <div className="min-h-screen overflow-hidden bg-[#f5f8fc] font-sans text-slate-700 antialiased selection:bg-cyan-200 selection:text-[#06204e]">
    <style>{`
      @keyframes orbit-one { to { transform:translateY(-50%) rotate(360deg); } }
      @keyframes orbit-two { to { transform:translateY(-50%) rotate(-360deg); } }
      @keyframes cube { 0%,100% { transform:translateY(-50%) rotate(45deg) scale(.94); } 50% { transform:translateY(-50%) rotate(225deg) scale(1.12); } }
      @keyframes float-card { 0%,100% { transform:translateY(0); } 50% { transform:translateY(-8px); } }
      .field-grid { background-image:linear-gradient(rgba(125,211,252,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(125,211,252,.14) 1px,transparent 1px); background-size:36px 36px; mask-image:linear-gradient(90deg,transparent,black 60%,transparent); }.orbit-one { animation:orbit-one 12s linear infinite; }.orbit-two { animation:orbit-two 9s linear infinite; }.ai-cube { animation:cube 6s ease-in-out infinite; }.float-card { animation:float-card 5s ease-in-out infinite; } @media (prefers-reduced-motion:reduce) { .orbit-one,.orbit-two,.ai-cube,.float-card { animation:none; } }
    `}</style>
    <section className="relative isolate overflow-hidden bg-[#06204e] px-6 py-16 text-white md:px-12 md:py-24"><AiOrbitalVisual /><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.95fr] lg:items-center"><div><p className="inline-flex rounded-full border border-cyan-100/20 bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.18em] text-cyan-100">Food Safety & Anti-Terror Suite</p><h1 className="mt-7 max-w-4xl text-4xl font-black uppercase leading-[.9] tracking-[-.06em] sm:text-5xl lg:text-6xl">Food Poison<br /><span className="text-cyan-300">Detection Kit</span></h1><p className="mt-6 max-w-xl text-sm leading-7 text-blue-100/80">Portable, autonomous field testing designed for immediate food-safety screening.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-3 rounded-full bg-cyan-300 px-6 py-3.5 text-xs font-black uppercase tracking-wider text-[#06204e] transition hover:bg-white">Request product information <span className="text-lg">→</span></Link></div><div className="float-card relative ml-auto w-full max-w-sm rounded-[1.75rem] border border-white/15 bg-white/[.07] p-6 shadow-2xl backdrop-blur"><p className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-300">AI Analysis Node</p><div className="mt-6 space-y-4"><div className="flex items-center justify-between border-b border-white/10 pb-3 text-xs"><span className="text-blue-100/70">Model</span><strong>STPD-06</strong></div><div className="flex items-center justify-between border-b border-white/10 pb-3 text-xs"><span className="text-blue-100/70">Interpretation</span><strong className="text-cyan-300">Colorimetric</strong></div><div className="flex items-center justify-between text-xs"><span className="text-blue-100/70">Results window</span><strong>2–8 minutes</strong></div></div></div></div></section>

    <main className="mx-auto max-w-7xl space-y-16 px-6 py-16 md:px-12 md:py-24">
      <section className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><aside className="space-y-5 lg:sticky lg:top-24 lg:self-start"><div className="overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white p-4 shadow-[0_14px_40px_rgba(15,52,103,.07)]"><p className="mb-3 text-[10px] font-black uppercase tracking-[.18em] text-[#1676c6]">STPD-06 Field Kit Reference</p><div className="relative aspect-[3/2] overflow-hidden rounded-2xl bg-[#edf8ff]"><Image src="/food-poison1.jpg" alt="STPD-06 Food Poison Detection Kit Diagram" fill priority className="object-contain p-2 transition duration-700 hover:scale-105" /></div><p className="mt-3 text-center text-[10px] italic text-slate-400">Figure 1: STPD-06 Autonomous Testing Apparatus</p></div><div className="overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white p-4 shadow-sm"><p className="mb-3 text-[10px] font-black uppercase tracking-[.18em] text-[#1676c6]">Technical Verification Overview</p><div className="relative aspect-[3/2] overflow-hidden rounded-2xl bg-[#edf8ff]"><Image src="/food-poison2.jpg" alt="Food Poison Kit Operational Testing Reference" fill className="object-contain p-2 transition duration-700 hover:scale-105" /></div><p className="mt-3 text-center text-[10px] italic text-slate-400">Figure 2: Colorimetric Interpretation Guide</p></div></aside>
      <div className="rounded-[1.75rem] border border-slate-200 bg-white p-7 shadow-sm md:p-10"><div className="border-b border-slate-100 pb-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#1676c6]">Autonomous field diagnostics</p><h2 className="mt-3 text-2xl font-black leading-tight text-[#06204e] md:text-3xl">Introduction to &apos;STPD-06&apos; Short Term Poison Detection Kit</h2><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold tracking-wider text-slate-500">Model: STPD-06</span><span className="rounded-full bg-cyan-100 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[#0b3777]">Global Defense Standard</span></div></div><div className="mt-7 space-y-4 text-sm leading-7 text-slate-600"><p>Our Field detection kit for Poison in Food is called <strong>&apos;STPD-06&apos; (Short Term Poison Detection Kit)</strong>. The Poison Detection kits are presently being used by the <strong>US Department of Defense (DOD)</strong>, the <strong>British Ministry of Defense (MOD)</strong>, as well as in many other countries. Several entities within the US DOD validate its performance independently and recommend its use.</p><p>The detectors were developed for the DOD and were tested extensively using more than <strong>12,000 different foods</strong>, cooking methods, spices, etc. Our Poison Detection Kit has been noted a Success Story and can be found on the web page of TSWG, the US Government arm for research on anti-terror technology.</p><p>To the best of our knowledge, our poison detection kits are the only detectors available in the world that detects poisons <strong>INSTANTLY, RELIABLY</strong>, and which can be used even by a person with no technical background.</p></div><div className="mt-7 rounded-2xl bg-[#0b3777] px-5 py-4 text-center text-xs font-black uppercase tracking-wider text-cyan-100 shadow-lg">Results are obtained in 2-8 minutes for all thirty poisons.</div></div></section>

      <section className="rounded-[1.75rem] bg-[#e8f6ff] p-7 md:p-10"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#1676c6]">Operational design</p><h2 className="mt-3 text-2xl font-black text-[#06204e]">Features of &apos;STPD-06&apos; Food Poison Detection Kits</h2></div><ul className="grid gap-3 sm:grid-cols-2">{features.map((feature, index) => <li key={index} className="flex gap-3 rounded-2xl border border-white bg-white/85 p-4 text-xs leading-5 text-slate-600 shadow-sm"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#0b3777] text-cyan-300"><CheckIcon /></span><span>{feature}</span></li>)}</ul></div></section>

      <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[1.75rem] border border-slate-200 bg-white p-7 shadow-sm md:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#1676c6]">Detection architecture</p><h2 className="mt-3 text-2xl font-black text-[#06204e]">Integrated Detector Modules</h2><div className="mt-7 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-slate-200 p-4"><span className="text-[10px] font-black text-cyan-600">01</span><h3 className="mt-3 text-sm font-bold text-[#06204e]">CA Detector</h3><p className="mt-2 text-xs leading-5 text-slate-600">Detects cyanides, azides, sulfides and chromates.</p></article><article className="rounded-2xl border border-slate-200 p-4"><span className="text-[10px] font-black text-cyan-600">02</span><h3 className="mt-3 text-sm font-bold text-[#06204e]">HM Detector</h3><p className="mt-2 text-xs leading-5 text-slate-600">Detects cadmium, lead, mercury and thallium.</p></article><article className="rounded-2xl border border-slate-200 p-4"><span className="text-[10px] font-black text-cyan-600">03</span><h3 className="mt-3 text-sm font-bold text-[#06204e]">AJ Pouch</h3><p className="mt-2 text-xs leading-5 text-slate-600">Detects <strong>ALL</strong> arsenic compounds.</p></article></div></div><aside className="rounded-[1.75rem] bg-[#06204e] p-7 text-white shadow-xl md:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">Advanced Matrix Diagnostics</p><p className="mt-5 text-sm leading-7 text-blue-100/80">The Poison Detectors used in the CKT kits were optimized using over 12,000 food samples from all around the world including Indian food. Although the detectors appear simple, they are advanced systems designed to isolate poisons which a person may consume without suspecting any threat. Highly salty laboratory-prepared artificial mixtures are filtered out if they alter taste profiles naturally, preventing false-positive clutter.</p><div className="mt-7 flex justify-between border-t border-white/10 pt-5 text-[10px] italic text-blue-100/60"><span>Security Screening Solution</span><span>Powered by ChemSee</span></div></aside></section>
    </main>
  </div>;
}
